### ISSUE TITLE
default level -P seems to be broken: Invalid arguments: option -P requires argument! (Debian #1024612)

### ISSUE THREAD

**Issue by teward** [pastebinit/pastebinit#1]
Forwarded from Debian Bug #1024612 - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024612

> Package: pastebinit
> Version: 1.6.2-1
> Severity: normal
> 
> The pastebinit -P option seems to now require an argument even though
> the option didn't require one before and the docs mention a default.
> 
> This seems to be a regression from the version in Debian bullseye.
> 
> More details of the error and documentation:
> 
>    $ pastebinit -P |& grep -- -P
>    Invalid arguments: option -P requires argument!
>    	-P <private level> (default is '1')
>    
>    $ man pastebinit  | grep -- -P
>           -P [private level] (default: 1)
>    
>    $ pastebinit -P 
>    Invalid arguments: option -P requires argument!
>    
>    pastebinit v1.6.2
>    
>    Reads on stdin for input or takes a list of files as parameters
>    
>    Usage:	pastebinit [OPTION...] [FILE...]
>    
>    General arguments:
>    
>    	-b <pastebin> (default is 'paste.debian.net')
>    	-i <input file>
>    	-l List all supported pastebins
>    	-E Print the content to stdout too
>    	-h Print this help screen
>    	-v Print the version number
>    	-V Print verbose output to stderr
>    
>    Optional arguments (not supported by all pastebins):
>    
>    	-a <author> (default is 'pabs')
>    	-t <title of paste> (default is none)
>    	-f <format of paste> (default is 'text')
>    	-j <jabberid> (default is '')
>    	-m <permatag> (default is none)
>    	-P <private level> (default is '1')
>    	-u <username> -p <password>
>    
> -- System Information:
> Debian Release: bookworm/sid
>   APT prefers testing-debug
>   APT policy: (900, 'testing-debug'), (900, 'testing'), (800, 'unstable-debug'), (800, 'unstable'), (790, 'buildd-unstable'), (700, 'experimental-debug'), (700, 'experimental'), (690, 'buildd-experimental')
> merged-usr: no
> Architecture: amd64 (x86_64)
> 
> Kernel: Linux 6.0.0-4-amd64 (SMP w/4 CPU threads; PREEMPT)
> Kernel taint flags: TAINT_OOT_MODULE, TAINT_UNSIGNED_MODULE
> Locale: LANG=en_AU.utf8, LC_CTYPE=en_AU.utf8 (charmap=UTF-8), LANGUAGE=en_AU:en
> Shell: /bin/sh linked to /bin/dash
> Init: systemd (via /run/systemd/system)
> LSM: AppArmor: enabled
> 
> Versions of packages pastebinit depends on:
> ii  python3         3.10.6-1
> ii  python3-distro  1.8.0-1
> 
> pastebinit recommends no packages.
> 
> pastebinit suggests no packages.
> 
> -- no debconf information

**Comment by krytarik** [comment]
> The pastebinit -P option seems to now require an argument even though the option didn't require one before...

Yes, because 1.) this allows one to both enable and disable private pasting via command-line option which wasn't possible before, and 2.) there are pastebins that offer multiple levels on private pastes.

> ...and the docs mention a default.

Yes, like there are defaults on other options that require an argument when specified on the command line. So in this case, if you just want to make a private paste (and the bin only got one level of privacy), since the default is indeed `1` now whereas before private pasting was disabled by default, you'd not need to pass the option at all.
