### ISSUE TITLE
dose this repositary had python3 pachages?

### ISSUE THREAD

**Issue by Paper-Dragon** [pastebinit/pastebinit#8]
maybe python3 package is more easy to use.

**Comment by teward** [comment]
This already is a Python3 program.  When you say "packages" what do you mean?

**Comment by Paper-Dragon** [comment]
use pip command `pip install package-name` to install pasteinit.
and use `import package-name` import this package

**Comment by teward** [comment]
pastebinit was originally written to be a standalone Python script/program.  It was not designed to be used programmatically.

Even if this were on PyPI, it would not be written in a way you can programmatically import into another script.  It was not written with that in mind.

**Comment by Paper-Dragon** [comment]
okay, thank u.
